Added feature to redirect to the primary domain
lorinkoz/django-pgschemas pull request #98
Opened 2021-10-28 14:36 UTC by ktowen

Added the feature to mark a domain or folder as a redirection to the primary domain of a dynamic tenant.

2021-11-19 17:34 UTC, lorinkoz requested changes
Nicely done! Just please see a couple of comments.

2021-11-19 17:34 UTC, lorinkoz commented on django_pgschemas/middleware.py
> +                    primary_domain = tenant.domains.get(is_primary=True)
No recuerdo si en otras partes del codigo hemos asumido que `is_primary=True` es único por domain, o siquiera que haya un dominio primario siempre. Por favor revisa, y si lo hemos hecho con recelo, _sugiero_ cambiar esto a `filter.first` y tener en cuenta el caso `None`. Solo una sugerencia.

2021-11-19 17:34 UTC, lorinkoz commented on django_pgschemas/middleware.py
> +                    return redirect(primary_domain.absolute_url(path), permanent=True)
Preferiría que no fuera una redirección permanente, dado que el valor en la BD puede cambiar.

2021-11-19 22:43 UTC, ktowen commented on django_pgschemas/middleware.py
> +                    primary_domain = tenant.domains.get(is_primary=True)
En https://github.com/lorinkoz/django-pgschemas/blob/master/django_pgschemas/models.py#L129-L132 se esta comprobando al salvar un domain que solo haya un primary y que si no existe lo hace primary automaticamente. Me parece que si no hay un dominio primario se debe fallar con ruido porque es un error en otro lado. 

En caso de permitir que primary_domain sea None cual deberia ser el comportamiento si no lo encuentra? Aceptar esa url como dominio valido y servir el sitio desde ahi?

2021-11-19 22:48 UTC, ktowen commented on django_pgschemas/middleware.py
> +                    return redirect(primary_domain.absolute_url(path), permanent=True)
A qué te refieres con cambiar? que pueda dejar de ser una redirección? 
La redirección permanente tiene otras implicaciones para los navegadores y los crawlers. 
Si un usuario quiere una redirección es para deshacerse del dominio viejo y solo tener el nuevo, el caso de que vuelvan para atrás es poco probable. Imagino que de pasar eso se puede poner otra redirección en el anterior primary (y el usuario va a estar saltando de un lado para otro)

2021-11-20 20:56 UTC, lorinkoz commented on django_pgschemas/middleware.py
> +                    primary_domain = tenant.domains.get(is_primary=True)
- Aceptado lo de un solo primary.
- Si no hay primary, ignorar la redirección?

2021-11-20 20:59 UTC, lorinkoz commented on django_pgschemas/middleware.py
> +                    return redirect(primary_domain.absolute_url(path), permanent=True)
Mi preocupación es que al hacer una redirección permanente (301), eso puede ser cacheado en distintos lugares. Hacerla no permanente (302) da la oportunidad de cambiar el dominio principal en el futuro sin tener que fajarse contra el caché.

2021-11-24 19:57 UTC, merged